# GitHub Pages configuration
title: Under-water SONAR Image Classification
description: Train underwater SONAR image classification models and generate explanations using LIME-based Explainable Artificial Intelligence
show_downloads: false
