# GitHub Pages configuration
title: Under-water SONAR Image Classification
description: Train underwater SONAR image classification models and generate explanations using LIME-based Explainable Artificial Intelligence
author: Purushothaman Natarajan, Athira Nambiar
url: https://purushothaman-natarajan.github.io/Under-water-sonar-image-classification
show_downloads: false

# SEO
plugins:
  - jekyll-seo-tag
